[package]
name = "bin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
compiler = { path = "../../powdr/compiler" }
riscv = { path = "../../powdr/riscv" }
riscv_executor = { path = "../../powdr/riscv_executor" }
number = { path = "../../powdr/number" }
models = { path = "../models" }
hex = "0.4.3"
env_logger = "0.10.0"
thiserror = "1.0"
revm = { path = "../../revm/crates/revm", features = [ "serde" ] }
serde_json = "1.0.108"
walkdir = "2.4.0"
